"""tokens

Revision ID: 6010e4a1f485
Revises: eb69a2c69d2f
Create Date: 2022-01-08 00:29:41.563504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6010e4a1f485'
down_revision = 'eb69a2c69d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
