"""Selected coloum added

Revision ID: 821f4b0c6f94
Revises: 6010e4a1f485
Create Date: 2022-01-23 21:23:40.301019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821f4b0c6f94'
down_revision = '6010e4a1f485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Selected',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['Jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seeker_id'], ['Seekers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Selected')
    # ### end Alembic commands ###
