"""relation ship implemented

Revision ID: eb69a2c69d2f
Revises: a3e5c5ca5e05
Create Date: 2022-01-07 21:37:54.250495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb69a2c69d2f'
down_revision = 'a3e5c5ca5e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
